### ISSUE TITLE
No messages on proudct page

### ISSUE THREAD

**Issue by derrtas** [husseycoding/backorder#11]
Hi

I have installed your current plugin version on magento 1.8.0.0 and I can't see "estimated delivery" message on product page with my custom theme on. I can see it on any default magento theme. Just to confirm i use core price.phtml block (i can see this block shows the message in other templates).

Any idea what can cause the problem? I really would like to make this work on my custom theme

**Comment by husseycoding** [comment]
First things to check is that you have the extension configured so that it will actually show content according to this flowchart:

https://raw.githubusercontent.com/husseycoding/backorder/master/flowchart.png

If you think things are configured correctly then make sure your price template has not been modified from the original.  Have a look at the frontend JS to see the elements the dispatch estimate text is attached to.

https://github.com/husseycoding/backorder/blob/master/skin/frontend/base/default/js/backorder.js

**Comment by husseycoding** [comment]
Assuming this is an issue restricted to the users theme rather than an issue with the extension.
