### ISSUE TITLE
Configurable Products

### ISSUE THREAD

**Issue by markessex** [husseycoding/backorder#13]
Hello, I am using Magento 1.9.2.1. I am having an issue where the back order information is not showing on the product page for configurable products, I have selected an size within the product which does not work, the only time I am shown any info regarding dispatch is from the basket when a configurable product has been added. There are no problems with simple products.

Can you let me know if this is a bug or do I have a setting wrong somewhere?

Thanks. 

p.s additional point: Each simple product from within the configurable product has a lead time and handling time set correctly (i.e 1 day).

**Comment by husseycoding** [comment]
Firstly, can you make sure you have the products configured such that it should display dispatch estimates according to the flow chart linked to in the settings.  Assuming this is configured correctly is it working correctly on a clean install of Magento?  It may be that the HTML elements to attach the estimates to have been removed or modified in your theme such that the extension cannot find them.

**Comment by markessex** [comment]
Hello,

Thank you, I have checked the configuration which is correct. I have also checked the product listing for a configurable item, the code is present:

//<![CDATA[
            var thisbackorder = new backorder();
                                    thisbackorder.isproduct = true;
            thisbackorder.iscart = false;
            thisbackorder.estimatetext = "Estimated dispatch";
            thisbackorder.orderbefore = 0;
            thisbackorder.orderbeforetodaytext = "Dispatched today if ordered within the next";
            thisbackorder.orderbeforetomorrowtext = "Dispatched tomorrow if ordered within the next";
            thisbackorder.orderbeforelatertext = "Dispatched on";
            thisbackorder.noleadtimestamp = "1452008518";
            thisbackorder.noleaddatestring = "Tuesday, 5th January";
            thisbackorder.cutoff = "1452013200";
            thisbackorder.now = "1452008518";
            thisbackorder.orderbeforestring = false;
                            thisbackorder.producttype = "configurable";
                                                            thisbackorder.productestimate = {"277":"Wednesday, 6th January"};
                                                    thisbackorder.showorderbefore = {"277":true};

**Comment by husseycoding** [comment]
Does it work correctly on clean install of Magento?

**Comment by dchigit** [comment]
Hello, I am using Magento 1.9.2.2. I have the same issue as described before. I checked the configuration and tried the extension on a clean install of Magento with both rwd and default themes (my theme is rwd) also with different configurations, but the problem it's still the same.

**Comment by husseycoding** [comment]
Ok thanks for testing on a clean install, I'll do some tests locally and see what I find.

**Comment by husseycoding** [comment]
I have tested the latest extension version on a clean 1.9.2.2 CE install and dispatch estimates are showing correctly for configurable products on the product page.  One thing to check is that you have not modified your theme to remove an element on the page with class `price-box` - this element is required for configurable products.

Closing as it does not seem like there is a problem as described with the extension, if you think otherwise update the issue with the reasons why.

**Comment by markessex** [comment]
I have checked the code, the price-box div you are referring to does display (otherwise wouldn't the price be missing as well?). Thank you for your help.

**Comment by husseycoding** [comment]
Quite often developers will change the HTML elements in a theme to have different classes, change where they are placed, etc.  Changing the position on the element is not an issue, but the extension requires the an element with class of `price-box` in order to position the dispatch estimate text - in a custom theme the element may still be there to show the price, but the class name could have been changed to something different in which case the dispatch estimates would not display.

If you find any more specifics on when/why the dispatch estimates are not showing for you (i.e. shows configured one way but not another) then feel free to update the issue.
