### ISSUE TITLE
Backorder button not showing

### ISSUE THREAD

**Issue by Brakoops** [husseycoding/backorder#17]
My issue is based on an assumption, I suspect when all actions relevant for this module are correctly done, a product not in stock will show a backorder button.

I have tried to get this shown, but to no effect. Currently, the (test) [website](http://systemcare-ict.nl/magento/index.php/matrijzen/mubea-matrijs-rond-nr-3/mubea-matrijs-nr-3-3-7mm.html) has been reset to a clean Magento 1.9.2.4 installation and the only extension is the Backorder extension. 

I thought I followed the flowchart, but clearly I am missing something?

**Comment by husseycoding** [comment]
The extension doesn't show a backorder button as Magento has backorder functionality built in.  It instead shows the estimated dispatch date (which I can see you are getting) and what is displayed here is affected by the backorder configuration.  The idea of the extension is to tell the customer when they can expect a backordered item to be dispatched, so they are able to order the product as normal (assuming placing a backorder is allowed for that product), and rather than expecting a fast dispatch time like when the product is in stock, they are informed that there will be a delay.
